config/routes.rb
Rails.application.routes.draw do

  resources :cats
  resources :cat_rental_requests
  resources :users, only: [:new, :create, :show]
  resource :session

  patch 'cat_rental_requests/:id/approve' =>
    'cat_rental_requests#approve', as: :approve

  patch 'cat_rental_requests/:id/deny' =>
    'cat_rental_requests#deny', as: :deny

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates :name, :user_id, :birth_date, :color, :sex, :description, :age, presence: true
  validates :age, numericality: true
  validates_inclusion_of :sex, in: %w( M F )

  has_many(
    :requests,
    :class_name => "CatRentalRequest",
    :foreign_key => :cat_id,
    :primary_key => :id,
    dependent: :destroy
  )
  
  belongs_to(
    :owner,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, :user_id, presence: true
  validates_inclusion_of :status, in: %w( PENDING APPROVED DENIED )
  validate :good_date_range
  validate :no_overlapping_requests

  belongs_to(
    :cat,
    :class_name => "Cat",
    :foreign_key => :cat_id,
    :primary_key => :id
  )

  belongs_to(
    :requester,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  def good_date_range
    unless self.start_date < self.end_date
      errors.add(:start_date, "Start date can't be after end date!")
    end
  end

  def overlapping_approved
    overlapping_requests.select { |request| request.status == "APPROVED" }
  end

  def overlapping_requests
    overlaps = []
    same_cat_requests.each do |request|
      if same_time_requests.include?(request)
        overlaps << request
      end
    end
  end

  def same_cat_requests
    CatRentalRequest.where("cat_id = #{self.cat_id}")
  end

  def same_time_requests
    CatRentalRequest.where("NOT (start_date >= ? OR end_date <= ?)", self.end_date, self.start_date)
  end



  def approve!
    self.overlapping_requests.each do |request|
      request.deny!
    end

    self.status = "APPROVED"
    self.save!
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end

  def no_overlapping_requests
    unless self.overlapping_approved.empty?
      errors.add(:start_date, "Your request overlaps with an approved request!")
    end
  end
end

app/models/session.rb
class Session <ActiveRecord::Base
  belongs_to(
    :user
  )
  

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many(
    :cats,
    class_name: "Cat",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many(
    :requests,
    class_name: "CatRentalRequest"
  )

  has_many(
    :sessions
  )

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by username: username
    if user.is_password?(password)
      user
    else
      nil
    end
  end

  def delete_session_token!(session_token)
    Session.find_by_token(session_token).delete
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def login!(user)
    @current_user = user
    session[:session_token] = Session.create!( {
      user_id: user.id,
      token: User.generate_session_token } ).token
  end

  def logout!(user)
    current_user.delete_session_token!(session[:session_token])
    session[:session_token] = nil
  end

  def already_logged_in
    redirect_to cats_url if current_user
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= Session.find_by_token(session[:session_token]).try(:user)
  end

  def not_logged_in_redirect
    redirect_to new_session_url unless !@current_user
  end

end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :not_logged_in_redirect

  def index
    @rental_requests = CatRentalRequest.all
    render :index
  end

  def new
    @rental_request = CatRentalRequest.new
    @cats = Cat.all
    render :new
  end

  def create
    @rental_request = CatRentalRequest.new(rental_request_params)
    @rental_request.user_id = current_user.id

    if @rental_request.save
      redirect_to cat_url(@rental_request.cat_id)
    else
      @cats = Cat.all
      render :new
    end
  end

  def show
    @rental_request = CatRentalRequest.find(params[:id])
    render :show
  end

  def approve
    @rental_request = CatRentalRequest.find(params[:id])
    @rental_request.approve!
    redirect_to cat_url(Cat.find(@rental_request.cat_id))
  end

  def deny
    @rental_request = CatRentalRequest.find(params[:id])
    @rental_request.deny!
    redirect_to cat_url(Cat.find(@rental_request.cat_id))
  end

  private

  def rental_request_params
    params.require(:cat_rental_request).permit(:start_date, :end_date, :cat_id)
  end



end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  COLORS = ["Brown", "Black", "Grey", "Orange", "Calico", "White"]

  before_action :must_be_owner,  only: [:update, :edit, :destroy]

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @colors = COLORS
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @colors = COLORS
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])


    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def destroy
    Cat.find(params[:id]).destroy
    redirect_to cats_url
  end

  private

  def cat_params
    params.require(:cat).permit(
      :name,
      :age,
      :birth_date,
      :sex,
      :color,
      :description
    )
  end

  def must_be_owner
     unless current_user.id == Cat.find(params[:id]).user_id
       redirect_to new_session_url
     end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_logged_in, only: [:new]

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render text: "Wrong credentials"
    else
      login!(user)
      redirect_to cats_url
    end
  end

  def destroy
    logout!(current_user)
    redirect_to new_session_url
  end

  private


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_logged_in, only: [:new]

  def new
    @user = User.new
    render :new
  end

  def create
    user = User.new(user_params)

    if user.save
      login!(user)
      redirect_to cats_url
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cat_rental_requests/index.html.erb
<ul>
  <% @rental_requests.each do |request| %>
    <li><a href="<%= cat_rental_request_url(request) %>">
      <%= Cat.find(request.cat_id).name %> : <%= request.start_date%> :

    </a> <%= request.status%></li>

  <%end%>
</ul>

app/views/cat_rental_requests/new.html.erb
<h1>So you want to rent a cat...</h1>

<form action="<%= cat_rental_requests_url %>" method="post">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>
    Please select your cat!
    <select name="cat_rental_request[cat_id]">
      <option value="blank"> </option>
      <% @cats.each do |cat| %>
        <option value="<%= cat.id %>"><%= cat.name %></option>
      <% end %>
    </select>
  </label>
  <br>

  <label>
    Start date for your rental?
    <input type="date" name="cat_rental_request[start_date]" value="<%= @rental_request.start_date %>">
  </label>
  <br>

  <label>
    End date for your rental?
    <input type="date" name="cat_rental_request[end_date]" value="<%= @rental_request.end_date %>">
  </label>
  <br>

  <button>Submit rental!</button>

app/views/cat_rental_requests/show.html.erb
<h1>Request number <%= @rental_request.id %></h1>

<%= Cat.find(@rental_request.cat_id).name %><br>
Start date: <%= @rental_request.start_date %><br>
End date: <%= @rental_request.end_date %><br>
Status: <%= @rental_request.status %>

<% if current_user.id == @rental_request.requester.id %>
  <%= button_to "Cancel your request",
      cat_rental_request_url,
      method: :delete %>
<% end %>

app/views/cats/_form.html.erb
<h1><%=
  if cat.persisted?
    "Edit #{cat.name}!"
  else
    "Create new cat!"
  end
  %></h1>

<form action=<%=
  if cat.persisted?
    "#{cat_url(cat)}"
  else
    "#{cats_url}"
  end
  %> method="post">
  
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden" name="_method" value=<%=
  if cat.persisted?
    "patch"
  else
    "post"
  end
  %>
  >

<label>
  Name
  <input type="text", name="cat[name]", value="<%= cat.name %>">
</label>
<br>

<label>
  Birthday
  <input type="date", name="cat[birth_date]", value="<%= cat.birth_date %>">
</label>
<br>

<label>
  Age
  <input type="text", name="cat[age]", value="<%= cat.age %>">
</label>
<br>

<label>
  <strong>Sex</strong>
  <br>
  <label>
    Male<input type="radio" name="cat[sex]" value="M"
      <%= "checked" if cat.sex == "M" %>>
  </label>

  <label>
    Female<input type="radio" name="cat[sex]" value="F"
      <%= "checked" if cat.sex == "F" %>>
  </label>

</label>
<br>

  <label>
    Color
    <select name="cat[color]">
      <option value="blank"> </option>
      <% colors.each do |color| %>
        <option value="<%= color %>"<%= "selected" if color == cat.color %>>            <%= color %>
        </option>
      <% end %>
    </select>
  </label>
  <br>

<textarea rows="10" cols="20" name="cat[description]">
  <%= cat.description %>
</textarea>
<br>

<button>Save Changes</button>
</form>

app/views/cats/edit.html.erb
<%= render partial: "form", locals: {cat: @cat, colors: @colors} %>

<!--<h1>Edit <%=@cat.name%>!</h1>

<form action="<%= cat_url(@cat) %>" method="post">
  <input type="hidden" name="_method" value="patch">



<label>
  Name
  <input type="text", name="cat[name]", value="<%= @cat.name %>">
</label>
<br>

<label>
  Birthday
  <input type="date", name="cat[birth_date]", value="<%= @cat.birth_date %>">
</label>
<br>

<label>
  Age
  <input type="text", name="cat[age]", value="<%= @cat.age %>">
</label>
<br>

<label>
  <strong>Sex</strong>
  <br>
  <label>
    Male<input type="radio" name="cat[sex]" value="M"
      <%= "checked" if @cat.sex == "M" %>>
  </label>

  <label>
    Female<input type="radio" name="cat[sex]" value="F"
      <%= "checked" if @cat.sex == "F" %>>
  </label>

</label>
<br>

  <label>
    Color
    <select name="cat[color]">
      <option value="blank"> </option>
      <% @colors.each do |color| %>
        <option value="<%= color %>"<%= "selected" if color == @cat.color %>>            <%= color %>
        </option>
      <% end %>
    </select>
  </label>
  <br>

<textarea rows="10" cols="20" name="cat[description]">
  <%= @cat.description %>
</textarea>
<br>

<button>Save Changes</button>
</form> -->

app/views/cats/index.html.erb
<h1>Our Cats!</h1>

<ul>
  <% @cats.each do |cat| %>
    <li><a href="<%= cat_url(cat) %>"><%=cat.name%></a></li>

  <%end%>
</ul>

<%= button_to "Request a cat!", new_cat_rental_request_url, method: :get %>

app/views/cats/new.html.erb
<%= render partial: "form", locals: {cat: @cat, colors: @colors} %>

<!--<h1>Add a new cat!</h1>

<form action="<%= cats_url %>" method="post">

  <label>
    Name
    <input type="text" name="cat[name]" value="<%= @cat.name %>">
  </label>
  <br>

  <label>
    Birthday
    <input type="date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
  </label>
  <br>

  <label>
    Age
    <input type="text" name="cat[age]" value="<%= @cat.age %>">
  </label>
  <br>

  <label>
    <strong>Sex</strong>
    <br>
    <label>
      Male<input type="radio" name="cat[sex]" value="M">
    </label>

    <label>
      Female<input type="radio" name="cat[sex]" value="F">
    </label>

  </label>
  <br>

  <label>
    Color
    <select name="cat[color]">
      <option value="blank" selected> </option>
      <% @colors.each do |color| %>
        <option value="<%= color %>>"><%= color %></option>
      <% end %>
    </select>
  </label>
  <br>

  <textarea rows="10" cols="20" name="cat[description]">
    Tell us about your cat!
  </textarea>

  <br>
  <button>Save Cat</button>

</form> -->

app/views/cats/show.html.erb
<h1><%=@cat.name%></h1>

<table>
  <tr>
    <td>Age</td>
    <td><%=@cat.age%><td>
  </tr>
  <tr>
    <td>Birth Date</td>
    <td><%=@cat.birth_date%><td>
  </tr>
  <tr>
    <td>Sex</td>
    <td><%=@cat.sex%><td>
  </tr>
  <tr>
    <td>Color</td>
    <td><%=@cat.color%><td>
  </tr>
  <tr>
    <td>Description</td>
    <td><%=@cat.description%><td>
  </tr>
</table>
<br>

<table>
  Current rental requests for <%= @cat.name %>
  <% @cat.requests.sort_by { |request| request.start_date }.each do |request| %>
    <tr>
      <td><%= request.start_date %></td>
      <td><%= request.end_date %></td>
      <td><%= User.find(request.user_id).username%></td>
      <td><%= request.status %></td>

      <td>
        <% if current_user.id == @cat.user_id && request.status == "PENDING" %>
          <%= button_to "Approve", approve_url(request), method: :patch %>
        <% end%>
      </td>
      <td>
        <% if current_user.id == @cat.user_id && request.status == "PENDING" %>
          <%= button_to "Deny", deny_url(request), method: :patch %>
        <% end%>
      </td>
    </tr>
  <% end %>

</table>
<br>

<% if current_user.id == @cat.user_id %>
<form action="<%= cat_url(@cat) %>" method="post">
  <input type="hidden" name="_method" value="delete">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <button>Delete this cat</button>

</form>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatRentalApp</title>
  <% if !current_user.nil?%>
  Hello, <%= current_user.username %>
  <br>
  <%= button_to "Logout", session_url, method: :delete %>
  <% end%>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1> Sign up! </h1>

<form action="<%= users_url %>" method="post">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>
    Username:
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>
  <br>

  <label>
    Password:
    <input type="password" name="user[password]">
  </label>
  <br>

  <button>Create user</button>

</form>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
  <br>
  You're the best!